### ISSUE TITLE
Butoane CHESTIONAR si CHAT de pe paigna principala

### ISSUE THREAD

**Issue by AndreiCnst30** [mbogdan2704/mps2#2]
Pasii pentru a reproduce: 
1. Deschiderea aplicatiei
2. Apasarea celor doua butoane   
Rezultat actual: Status Code: 404; Not   Found   
Rezultat asteptat: Trimiterea catre  paginile respective

**Comment by mbogdan2704** [comment]
Butoanele functioneaza acum corespunzator.
