### ISSUE TITLE
Buton DONEAZA nu face nimic

### ISSUE THREAD

**Issue by AndreiCnst30** [mbogdan2704/mps2#3]
Pasii pentru a reproduce:
1.	Deschiderea aplicatiei
2.	Deschiderea paginii MyDonations
3.	Alegerea unui pacient
4.	Apasarea butonului Doneaza
Rezultat actual: Nu se intampla nimic in urma apasarii butonului 
Rezultat asteptat: Incrementarea numarului de persoane care au donat.

**Comment by mbogdan2704** [comment]
O sa fie implementat in sprint-ul urmator

**Comment by vladAl96** [comment]
Done
